name: Sync from upstream
on:
  schedule:
    # 每天凌晨一点执行一次
    - cron:  '0 1 * * *'
  workflow_dispatch:  #run manually  

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        env:
          GITHUB_TOKEN: '${{ secrets.WFTOKEN }}' #token with `workflows` permission
        #with:
          #token: '${{ secrets.WFTOKEN }}'
      - name: sync from upstream
        env:
          SYNC_URL: 'https://github.com/spack/spack'
          SYNC_BRANCH: 'develop'
        run: |
          cp /usr/share/zoneinfo/Asia/Shanghai  /etc/localtime
          
          git remote add upstream  "$SYNC_URL"
          git branch -a
          #git fetch upstream
          #git checkout -b $SYNC_BRANCH upstream/$SYNC_BRANCH
          #git push --force origin $SYNC_BRANCH
